theme: jekyll-theme-slate
title: Mini-Curso
description: Fazendo teste com o github lorem ipsum lorem ipsum lorem ipsum lorem ipsum 
lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 
